name: Build AI OS (Android 15)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-17-jdk git curl python-is-python3 -y
          git config --global user.name "Ajay Dash"
          git config --global user.email "ajay@example.com"

      - name: Initialize repo
        run: |
          mkdir workspace
          cd workspace
          repo init -u https://github.com/AOSP-Next/manifest -b uvite --depth=1
          git clone https://github.com/Nuapali/local_manifests.git .repo/local_manifests
          repo sync -c --no-clone-bundle --no-tags -j4

      - name: Start build
        run: |
          cd workspace
          source build/envsetup.sh
          lunch aosp_citrus-userdebug
          mka bacon -j$(nproc --all)

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AIOS-citrus-Android15
          path: workspace/out/target/product/citrus/*.zip
