name: Build crDroid 10 for Citrus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Environment
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick \
        libncurses5-dev libncurses5-dev:i386 libreadline-dev:i386 zlib1g:i386 liblz4-tool libxml2-utils \
        lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-17-jdk repo -y

    - name: Init crDroid Source
      run: |
        mkdir rom
        cd rom
        curl https://storage.googleapis.com/git-repo-downloads/repo > repo
        chmod a+x repo
        ./repo init -u https://github.com/crdroidandroid/android.git -b 14.0 --depth=1
        ./repo sync -c --no-tags --no-clone-bundle --force-sync -j8

    - name: Clone Device Trees
      run: |
        cd rom
        git clone https://github.com/crdroidandroid/android_device_xiaomi_citrus.git -b 14.0 device/xiaomi/citrus
        git clone https://github.com/crdroidandroid/android_vendor_xiaomi_citrus.git -b 14.0 vendor/xiaomi/citrus
        git clone https://github.com/crdroidandroid/android_kernel_xiaomi_sm6115.git -b 14.0 kernel/xiaomi/sm6115

    - name: Start Build
      run: |
        cd rom
        source build/envsetup.sh
